### ISSUE TITLE
Running unit tests

### ISSUE THREAD

**Issue by jeverling** [qld-gov-au/ckanext-s3filestore#86]
Hi everybody, are the instructions for running the unit tests currently supposed to work? On Python 3 it fails for me due to a dependency on Pylons, which I don't think supports Python 3. Trying with a Python 2 Docker container, I was running into several missing packages.
Just wanted to ask if it's supposed to work, in case running tests is probably broken.

**Comment by duttonw** [comment]
Thanks for reaching out.

The tests do run on python2 and python3 you can see the github actions that runs them here: https://github.com/qld-gov-au/ckanext-s3filestore/blob/master/.github/workflows/ci.yml
the github actions show this off
https://github.com/qld-gov-au/ckanext-s3filestore/actions/runs/2471892441

You may need to use the docker containers stated in the ci.yml to get our results.

**Comment by jeverling** [comment]
Thank you! I'll look at the CI script to figure out how to run them on my end.

**Comment by ThrawnCA** [comment]
> Thank you! I'll look at the CI script to figure out how to run them on my end.

Note that line 39 in the GitHub Actions file specifies a different Docker container according to the CKAN version being used. CKAN 2.9 supports both Python 2 and Python 3, but uses different requirements files for them, while CKAN 2.8 only supports Python 2. So it's probable that you'll need to set up your test environment carefully.
